version: '3.4'
services:
  passgen-app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: go-password-generator-app
    depends_on:
      - mongodb
    image: golang
    env_file: "./.env"
    ports:
      - "8095:8095"
    networks:
      net:
        ipv4_address: 172.20.0.2

  mongodb:
    image: mongo
    container_name: mongodb-password-generator
    env_file: "./.env"
    ports:
      - "27018:27017"
    networks:
      net:
        ipv4_address: 172.20.0.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24