version: '3.4'
services:
  passgen-app:
    build:
      dockerfile: docker/Dockerfile_Server
      context: .
    container_name: go-password-generator-app
    depends_on:
      - mongodb
    image: golang
    env_file: "./.env"
    ports:
      - "8095:8095"
    networks:
      default:
        ipv4_address: 206.8.3.2

  mongodb:
    image: mongo
    container_name: mongodb-password-generator
    env_file: "./.env"
    volumes:
      - ./scripts/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "27018:27017"
    command: --auth
    networks:
      default:
        ipv4_address: 206.8.3.3

networks:
  default:
    external:
      name: password_gen_net_dev